### ISSUE TITLE
Show custom icon in showCustomAlert

### ISSUE THREAD

**Issue by cbenhagen** [zonble/flutter_platform_alert#1]
It would be nice if we could use a custom icon in `showCustomAlert`.

**Comment by zonble** [comment]
That sounds like a good idea. However, it involves how to unify how to represent the resource of the icons on difference platforms. Any idea?

**Comment by cbenhagen** [comment]
It would be great if we could just pass it the path to an image. Maybe what `tray_manager` does can serve as an inspiration? https://github.com/leanflutter/tray_manager/blob/main/lib/src/tray_manager.dart#L96-L114

On macOS it does this: https://github.com/leanflutter/tray_manager/blob/main/lib/src/tray_manager.dart#L96-L114
On Linux: https://github.com/leanflutter/tray_manager/blob/main/linux/tray_manager_plugin.cc#L100-L121
On Windows: https://github.com/leanflutter/tray_manager/blob/main/linux/tray_manager_plugin.cc#L100-L121

@lijy91 is there a chance you might want to help out one more time?

**Comment by zonble** [comment]
Implemented in 0.2.6.
