### ISSUE TITLE
 Text is not visible on Android.

### ISSUE THREAD

**Issue by honeboy** [zonble/flutter_platform_alert#15]
Device : Samsung Galaxy s10 5G

The button title is fine, but the windowtitle and text are not visible. It seems that it is drawn with the same white color as the background.
No problem on iOS.

**Comment by zonble** [comment]
Actually I am not able to test on all of the Android devices. But you can fork the project and try to modify flutter_platform_alert/android/src/main/res/values/styles.xml to changes the default dark theme.

**Comment by zonble** [comment]
Actually I am not able to test on all of the Android devices. But you can try to modidy flutter_platform_alert/android/src/main/res/values/styles.xm
