### ISSUE TITLE
error after installed flutter_platform_alert: ^0.5.0

### ISSUE THREAD

**Issue by maxdiable** [zonble/flutter_platform_alert#20]
hi, i have installed flutter_platform_alert: ^0.5.0 but when run my app flutter in console show this error:

Running Gradle task 'assembleDebug'...
e: C:\Users\devitis.massimo\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_platform_alert-0.4.0\android\src\main\kotlin\net\zonble\flutter_platform_alert\FlutterPlatformAlertPlugin.kt: (23, 7): Redeclaration: FlutterPlatformAlertPlugin
e: C:\Users\devitis.massimo\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_platform_alert-0.5.0\android\src\main\kotlin\net\zonble\flutter_platform_alert\FlutterPlatformAlertPlugin.kt: (23, 7): Redeclaration: FlutterPlatformAlertPlugin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_platform_alert:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1

this is my pubspeck.yaml:

name: cure_domiciliari
description: Cure Domiciliari
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_smart_dialog: ^4.9.4
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.5.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  intl: ^0.18.1
  sizer: ^2.0.15
  rflutter_alert: ^2.0.7
  connectivity_plus: ^5.0.1
  device_preview: ^1.1.0
  image: ^4.1.3
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  cookie_jar: ^4.0.8
  awesome_snackbar_content: ^0.1.3
  maps_launcher: ^2.2.0
  toastification: ^1.0.2
  change_app_package_name: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  another_flushbar: ^1.12.30
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.3
  firebase_messaging: ^14.7.5
  flutter_platform_alert: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by zonble** [comment]
Hi @maxdiable

Please clear your pub cache

```
flutter pub cache clean
flutter pub get
```

Your build system cached two copies of the plugin and it causes duplicated sysmbol error.
