### ISSUE TITLE
minSdkVersion is 21 that is too high

### ISSUE THREAD

**Issue by calcitem** [zonble/flutter_platform_alert#4]
Can it be downgrade to lower to make more apps can use this useful plugin?

Thank you!

See: https://github.com/calcitem/Sanmill/actions/runs/2443814256

**Comment by zonble** [comment]
Hi,

https://www.appbrain.com/stats/top-android-sdk-versions

SDK 21 is Android 5.0. According to AppBrain, the Android device running OS lower than 5.0 only take 1% of the whole market share. Do we really still need to support that?

**Comment by calcitem** [comment]
If 1 million people use an Android app that includes this useful plug-in, that means 10,000 people can't use.

Many places are not as rich as we are, such as Africa, Latin America.

This API was supported as early as API Level 1, so there should be little risk of lowering API Level.  Down to 19 is recommended, I have some Android 4.x phones and can do some testing. It is also possible to use an emulator for testing.  I'd like to help with this test.

**Comment by zonble** [comment]
AKAIK, Flutter supports SDK level 19 and higher and I think 19 sounds reasonable. I am working by day in Taipei time today but I can do it later.

Thanks!

**Comment by calcitem** [comment]
Thanks!

感謝你能夠在百忙之中創作了這個Plug-in並為之不斷改進！

**Comment by zonble** [comment]
Fixed in 0.2.7
