### ISSUE TITLE
iPad crash show customAlert iOS15.5

### ISSUE THREAD

**Issue by xunreal75** [zonble/flutter_platform_alert#8]
Hi

IPAD Crashs  on -->
await FlutterPlatformAlert.showCustomAlert

My Codesnippet

` final clickedButton =
                                await FlutterPlatformAlert.showCustomAlert(
                                    windowTitle:
                                        context.tr.invitebyname(friend.name),
                                    text: context.tr.tellcode(
                                        friend.name, friend.requestId),
                                    positiveButtonTitle: context.tr.sendlink,
                                    neutralButtonTitle: context.tr.copy,
                                    negativeButtonTitle: context.tr.understand,windowPosition: AlertWindowPosition.parentWindowCenter);`
                      
will terminate by 
Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x7fa7bb04ec00>) of style UIAlertControllerStyleActionSheet from FlutterViewController (<FlutterViewController: 0x7fa7bd009e00>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
CoreSimulator 802.6.1 - Device: iPad Air (5th generation) (E61C312C-89E9-4CFA-B27C-1CB779B12B5D) - Runtime: iOS 15.5 (19F70) - DeviceType: iPad Air (5th generation)
terminating with uncaught exception of type NSException

**Comment by zonble** [comment]
Fixed in 0.2.8.
